/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { UserRewardUpdateManyWithoutUsersInput } from "./UserRewardUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SmartContractUpdateManyWithoutUsersInput } from "./SmartContractUpdateManyWithoutUsersInput";
import { UserSpentUpdateManyWithoutUsersInput } from "./UserSpentUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => UserRewardUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserRewardUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserRewardUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  rewards?: UserRewardUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SmartContractUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SmartContractUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SmartContractUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  smartContracts?: SmartContractUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => UserSpentUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserSpentUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserSpentUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  userSpents?: UserSpentUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
