/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { UserRewardCreateNestedManyWithoutUsersInput } from "./UserRewardCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SmartContractCreateNestedManyWithoutUsersInput } from "./SmartContractCreateNestedManyWithoutUsersInput";
import { UserSpentCreateNestedManyWithoutUsersInput } from "./UserSpentCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => UserRewardCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserRewardCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserRewardCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  rewards?: UserRewardCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SmartContractCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SmartContractCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SmartContractCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  smartContracts?: SmartContractCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => UserSpentCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserSpentCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserSpentCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userSpents?: UserSpentCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
