/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ChatMessageCreateNestedManyWithoutUsersInput } from "./ChatMessageCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ChatThreadWhereUniqueInput } from "../../chatThread/base/ChatThreadWhereUniqueInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ServerCreateNestedManyWithoutUsersInput } from "./ServerCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => ChatMessageCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ChatMessageCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ChatMessageCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  chatMessages?: ChatMessageCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ChatThreadWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ChatThreadWhereUniqueInput)
  @IsOptional()
  @Field(() => ChatThreadWhereUniqueInput, {
    nullable: true,
  })
  chatThreads?: ChatThreadWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ServerCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ServerCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ServerCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  servers?: ServerCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
