/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ChatMessageUpdateManyWithoutUsersInput } from "./ChatMessageUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ChatThreadWhereUniqueInput } from "../../chatThread/base/ChatThreadWhereUniqueInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ServerUpdateManyWithoutUsersInput } from "./ServerUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ChatMessageUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ChatMessageUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ChatMessageUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  chatMessages?: ChatMessageUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ChatThreadWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ChatThreadWhereUniqueInput)
  @IsOptional()
  @Field(() => ChatThreadWhereUniqueInput, {
    nullable: true,
  })
  chatThreads?: ChatThreadWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ServerUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ServerUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ServerUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  servers?: ServerUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
