/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserService } from "../user.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserCreateInput } from "./UserCreateInput";
import { UserWhereInput } from "./UserWhereInput";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserUpdateInput } from "./UserUpdateInput";
import { User } from "./User";
import { ChatMessageFindManyArgs } from "../../chatMessage/base/ChatMessageFindManyArgs";
import { ChatMessage } from "../../chatMessage/base/ChatMessage";
import { ChatMessageWhereUniqueInput } from "../../chatMessage/base/ChatMessageWhereUniqueInput";
import { ChatThreadFindManyArgs } from "../../chatThread/base/ChatThreadFindManyArgs";
import { ChatThread } from "../../chatThread/base/ChatThread";
import { ChatThreadWhereUniqueInput } from "../../chatThread/base/ChatThreadWhereUniqueInput";
import { ServerFindManyArgs } from "../../server/base/ServerFindManyArgs";
import { Server } from "../../server/base/Server";
import { ServerWhereUniqueInput } from "../../server/base/ServerWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserControllerBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.create({
      data: data,
      select: {
        billingInformation: true,
        code_2Fa: true,
        createdAt: true,
        email: true,
        enabled_2Fa: true,
        expiredAt_2Fa: true,
        firstName: true,
        googleUid: true,
        id: true,
        lastName: true,
        loggedInAt: true,
        publicWalletAddress: true,
        roles: true,
        status: true,
        tokenExpirationAt: true,
        type_2Fa: true,
        updatedAt: true,
        username: true,
        userToken: true,
        verifiedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        billingInformation: true,
        code_2Fa: true,
        createdAt: true,
        email: true,
        enabled_2Fa: true,
        expiredAt_2Fa: true,
        firstName: true,
        googleUid: true,
        id: true,
        lastName: true,
        loggedInAt: true,
        publicWalletAddress: true,
        roles: true,
        status: true,
        tokenExpirationAt: true,
        type_2Fa: true,
        updatedAt: true,
        username: true,
        userToken: true,
        verifiedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        billingInformation: true,
        code_2Fa: true,
        createdAt: true,
        email: true,
        enabled_2Fa: true,
        expiredAt_2Fa: true,
        firstName: true,
        googleUid: true,
        id: true,
        lastName: true,
        loggedInAt: true,
        publicWalletAddress: true,
        roles: true,
        status: true,
        tokenExpirationAt: true,
        type_2Fa: true,
        updatedAt: true,
        username: true,
        userToken: true,
        verifiedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          billingInformation: true,
          code_2Fa: true,
          createdAt: true,
          email: true,
          enabled_2Fa: true,
          expiredAt_2Fa: true,
          firstName: true,
          googleUid: true,
          id: true,
          lastName: true,
          loggedInAt: true,
          publicWalletAddress: true,
          roles: true,
          status: true,
          tokenExpirationAt: true,
          type_2Fa: true,
          updatedAt: true,
          username: true,
          userToken: true,
          verifiedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          billingInformation: true,
          code_2Fa: true,
          createdAt: true,
          email: true,
          enabled_2Fa: true,
          expiredAt_2Fa: true,
          firstName: true,
          googleUid: true,
          id: true,
          lastName: true,
          loggedInAt: true,
          publicWalletAddress: true,
          roles: true,
          status: true,
          tokenExpirationAt: true,
          type_2Fa: true,
          updatedAt: true,
          username: true,
          userToken: true,
          verifiedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/chatMessages")
  @ApiNestedQuery(ChatMessageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ChatMessage",
    action: "read",
    possession: "any",
  })
  async findManyChatMessages(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<ChatMessage[]> {
    const query = plainToClass(ChatMessageFindManyArgs, request.query);
    const results = await this.service.findChatMessages(params.id, {
      ...query,
      select: {
        createdAt: true,
        fileTitle: true,
        fileUrl: true,
        id: true,
        message: true,

        thread: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/chatMessages")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectChatMessages(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ChatMessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatMessages: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/chatMessages")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateChatMessages(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ChatMessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatMessages: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/chatMessages")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectChatMessages(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ChatMessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatMessages: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/chatThreads")
  @ApiNestedQuery(ChatThreadFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ChatThread",
    action: "read",
    possession: "any",
  })
  async findManyChatThreads(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<ChatThread[]> {
    const query = plainToClass(ChatThreadFindManyArgs, request.query);
    const results = await this.service.findChatThreads(params.id, {
      ...query,
      select: {
        chatMessages: {
          select: {
            id: true,
          },
        },

        chatType: true,
        closedAt: true,
        createdAt: true,

        expertId: {
          select: {
            id: true,
          },
        },

        id: true,

        rates: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/chatThreads")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectChatThreads(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ChatThreadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatThreads: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/chatThreads")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateChatThreads(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ChatThreadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatThreads: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/chatThreads")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectChatThreads(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ChatThreadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatThreads: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/expertChatThread")
  @ApiNestedQuery(ChatThreadFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ChatThread",
    action: "read",
    possession: "any",
  })
  async findManyExpertChatThread(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<ChatThread[]> {
    const query = plainToClass(ChatThreadFindManyArgs, request.query);
    const results = await this.service.findExpertChatThread(params.id, {
      ...query,
      select: {
        chatMessages: {
          select: {
            id: true,
          },
        },

        chatType: true,
        closedAt: true,
        createdAt: true,

        expertId: {
          select: {
            id: true,
          },
        },

        id: true,

        rates: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/expertChatThread")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectExpertChatThread(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ChatThreadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      expertChatThread: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/expertChatThread")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateExpertChatThread(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ChatThreadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      expertChatThread: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/expertChatThread")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectExpertChatThread(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ChatThreadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      expertChatThread: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/servers")
  @ApiNestedQuery(ServerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Server",
    action: "read",
    possession: "any",
  })
  async findManyServers(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Server[]> {
    const query = plainToClass(ServerFindManyArgs, request.query);
    const results = await this.service.findServers(params.id, {
      ...query,
      select: {
        createdAt: true,
        deployedAt: true,
        description: true,
        id: true,
        name: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/servers")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectServers(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ServerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      servers: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/servers")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateServers(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ServerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      servers: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/servers")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectServers(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ServerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      servers: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
