/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  IsString,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { ServerCostUpdateManyWithoutServersInput } from "./ServerCostUpdateManyWithoutServersInput";
import { ServerLogUpdateManyWithoutServersInput } from "./ServerLogUpdateManyWithoutServersInput";
import { EnumServerStatus } from "./EnumServerStatus";
import { UserUpdateManyWithoutServersInput } from "./UserUpdateManyWithoutServersInput";

@InputType()
class ServerUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deployedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ServerCostUpdateManyWithoutServersInput,
  })
  @ValidateNested()
  @Type(() => ServerCostUpdateManyWithoutServersInput)
  @IsOptional()
  @Field(() => ServerCostUpdateManyWithoutServersInput, {
    nullable: true,
  })
  serverCosts?: ServerCostUpdateManyWithoutServersInput;

  @ApiProperty({
    required: false,
    type: () => ServerLogUpdateManyWithoutServersInput,
  })
  @ValidateNested()
  @Type(() => ServerLogUpdateManyWithoutServersInput)
  @IsOptional()
  @Field(() => ServerLogUpdateManyWithoutServersInput, {
    nullable: true,
  })
  serverLogs?: ServerLogUpdateManyWithoutServersInput;

  @ApiProperty({
    required: false,
    enum: EnumServerStatus,
  })
  @IsEnum(EnumServerStatus)
  @IsOptional()
  @Field(() => EnumServerStatus, {
    nullable: true,
  })
  status?: "WorkInProgress" | "Deployed" | "Running" | "Stopped";

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutServersInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutServersInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutServersInput, {
    nullable: true,
  })
  userId?: UserUpdateManyWithoutServersInput;
}

export { ServerUpdateInput as ServerUpdateInput };
